# -*- coding: utf-8 -*-
"""AI Code Assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NrF0gshm2hBWci4RrQFd-7J0lUp02Dlt
"""

import gradio as gr
import ast
import io
import contextlib
import pandas as pd
from datetime import datetime

# 🔍 Error Explanation
def explain_syntax_error(error_msg):
    msg = str(error_msg)

    if "expected an indented block" in msg:
        return "❌ Indentation Error → Add spaces after loop/if"
    elif "invalid syntax" in msg:
        return "❌ Invalid Syntax → Missing ':' or brackets"
    elif "unexpected indent" in msg:
        return "❌ Unexpected Indent → Remove extra space"
    else:
        return f"❌ Syntax Error → {msg}"

# ⏱️ Complexity Analysis
def analyze_complexity(code):
    loop_count = code.count("for") + code.count("while")

    if loop_count >= 2:
        return "⏱️ Time Complexity: O(n²)"
    elif loop_count == 1:
        return "⏱️ Time Complexity: O(n)"
    else:
        return "⏱️ Time Complexity: O(1)"

# ▶️ Run Code
def run_code(code):
    try:
        buffer = io.StringIO()
        with contextlib.redirect_stdout(buffer):
            exec(code, {})
        output = buffer.getvalue()

        if output.strip() == "":
            output = "⚠️ No output (maybe no print statement)"

    except Exception as e:
        output = f"❌ Runtime Error: {str(e)}"

    return output

# 💾 Save to CSV
def save_to_csv(code, analysis, complexity, output):
    file_path = "my_results.csv"

    data = {
        "Code": [code],
        "Analysis": [analysis],
        "Complexity": [complexity],
        "Output": [output],
        "Time": [str(datetime.now())]
    }

    df = pd.DataFrame(data)

    try:
        old_df = pd.read_csv(file_path)
        df = pd.concat([old_df, df], ignore_index=True)
    except:
        pass

    df.to_csv(file_path, index=False)

    return "✅ Saved to CSV"

# 🧠 Main Function
def analyze_code(code):

    # Error Detection
    try:
        ast.parse(code)
        analysis = "✅ No syntax errors detected\n\n"
    except SyntaxError as e:
        return explain_syntax_error(e), "-", "❌ Cannot run", "❌ Not Saved"

    # Suggestions
    if "for" in code:
        analysis += "💡 Loop detected\n\n"

    if "#" not in code:
        analysis += "⚠️ Add comments\n\n"

    if "while True" in code:
        analysis += "⚠️ Infinite loop risk\n\n"

    analysis += "🚀 Code looks good!"

    # Complexity
    complexity = analyze_complexity(code)

    # Output
    output = run_code(code)

    # Save
    save_status = save_to_csv(code, analysis, complexity, output)

    return analysis, complexity, output, save_status

# 📥 Download Function
def download_csv():
    return "my_results.csv"

# 🎨 UI
with gr.Blocks() as app:
    gr.Markdown("# 🤖 AI Code Assistant PRO")

    code_input = gr.Textbox(lines=15, placeholder="Paste Python code here...")

    submit_btn = gr.Button("Analyze")

    analysis_out = gr.Textbox(label="🔍 Error + Suggestions")
    complexity_out = gr.Textbox(label="⏱️ Complexity")
    output_out = gr.Textbox(label="💻 Output")
    save_out = gr.Textbox(label="💾 Save Status")

    gr.Markdown("### 📥 Download Results")

    download_btn = gr.Button("Download CSV")
    download_file = gr.File()

    # Analyze button
    submit_btn.click(
        analyze_code,
        inputs=code_input,
        outputs=[analysis_out, complexity_out, output_out, save_out]
    )

    # Download button
    download_btn.click(
        download_csv,
        outputs=download_file
    )

app.launch(share=True)